### PR TITLE
eslint, reformat code

### PR DESCRIPTION
**Pull request by JuhQ**
* Added eslint
* Fixed code formatting

### CODE REVIEW

**Comment by prdpx7** [comment]
hey thanks for the PR.
but build is failing, can you look for the issue?
i think it's because of `standard` dev-dependencies in test.js

**Comment by JuhQ** [comment]
Fixed

**Comment by prdpx7** [comment]
build is still failing for node 4.

**Comment by JuhQ** [comment]
Shiit, yeah, node v4 does not have object destructuring.
Next steps after this pr would be to transpile this project with babel to support new syntax on older platforms.

**Comment by prdpx7** [comment]
Hey thanks buddy for taking your precious time to refactoring this old code.✌️

**Pull request merged**
